name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: release-${{ github.run_number }}
        path: dist/

    - name: Create Release
      id: create_release
      uses: pipe-cd/actions-gh-release@v2.6.0
      env:
        token: ${{ secrets.GB_TOKEN }}
      with:
        tag: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        release_file: dist/sarlib.min.js
        prerelease: false


    - name: Publish Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: path/to/your/build/directory/*
        asset_name: release-${{ github.run_number }}.zip
        asset_content_type: application/zip
