name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v3.1.2
    #   with:
    #     name: release-${{ github.run_number }}
    #     path: dist/


    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: v1.0.${{ github.run_number }}
        body_path: release_notes.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: ./dist/sarlib.min.js
        body_path: release_notes.md
        token: ${{ github.token }}
      env:
        GITHUB_REPOSITORY: AccentioStudios/quinientas_historias_challenge_sar_lib

        # upload_url: ${{ steps.create_release.outputs.upload_url }}
        # asset_path: dist/
        # asset_name: release-v1.0.${{ github.run_number }}.zip
        # asset_content_type: application/gzip
