name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: release-${{ github.run_number }}
        path: dist/


    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # id: create_release
      # uses: actions/create-release@v1
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
      # with:
      #   draft: false
      #   prerelease: false
      #   release_name: ${{ steps.version.outputs.version }}
      #   tag_name: Release v1.0.${{ github.run_number }}
      #   body_path: release_notes.md


    - name: Publish Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: path/to/your/build/directory/*
        asset_name: release-${{ github.run_number }}.zip
        asset_content_type: application/zip
