name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 3
        delete_tag_pattern: v*
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # - name: Delete Older Releases
    #   uses: actions/delete-package-versions@v4.1.1
    #   with:
    #     package-name: '@500historias/sarlib'
    #     package-type: npm
    #     min-versions-to-keep: 3
    #     token: ${{ github.token }}

    # - name: Publish Release
    #   uses: softprops/action-gh-release@v0.1.15
    #   with:
    #     draft: false
    #     prerelease: false
    #     files: ./dist/sarlib.min.js
    #     tag_name: release-${{ github.run_number }}
    #     body_path: release_notes.md
    #     token: ${{ secrets.GITHUB_TOKEN }}

    
    - name: Publish package on NPM 📦
      run: npm publish --tag beta --access public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
