name: Build and Release
on: 
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Choose release type
        options:
          - auto
          - patch
          - minor
          - major
        default: auto
        
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: git config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: npm credentials
      run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'
        cache: npm


    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TYPE_ARG: ${{ fromJSON('{"auto":"", "patch":":patch", "minor":":minor", "major":":major"}')[github.event.inputs.type] }}
      run: npm run release$TYPE_ARG
       

    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 6
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
    


