name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Bump version
      uses: TriPSs/conventional-changelog-action@v3.18.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        preset: 'conventionalcommits'
        git-message: 'chore(release): {version}'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'

    - name: Publish Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        draft: false
        prerelease: false
        name: build-${{ github.run_number }}
        files: ./dist/sarlib.min.js
        tag_name: build-${{ github.run_number }}
        body_path: CHANGELOG.md
        token: ${{ github.token }}

      # with:
      #   draft: false
      #   prerelease: true
      #   name: beta-${{ github.run_number }}
      #   files: ./dist/sarlib.min.js
      #   # tag_name: ${{ steps.changelog.outputs.tag }}
      #   tag_name: beta-${{ github.run_number }}
      #   body_path: CHANGELOG.md
      #   token: ${{ github.token }}
        

    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 6
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # - name: Delete Older Releases
    #   uses: actions/delete-package-versions@v4.1.1
    #   with:
    #     package-name: '@500historias/sarlib'
    #     min-versions-to-keep: 3
    #     package-type: npm
    #     delete-only-pre-release-versions: "true"
    #     token: ${{ secrets.GITHUB_TOKEN }}
    


    # - name: Publish package on NPM 📦
    #   run: npm publish --tag beta --access public
    #   env:
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
